"""Initial Migration

Revision ID: 500dbcdc6565
Revises: 
Create Date: 2020-05-12 15:01:05.222585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500dbcdc6565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket_list', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('bucket_list', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bucket_list', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket_list', type_='foreignkey')
    op.drop_column('bucket_list', 'date_modified')
    op.drop_column('bucket_list', 'created_by')
    # ### end Alembic commands ###
